### ISSUE TITLE
Problem with 0.2.1 of sbt-embedded-files

### ISSUE THREAD

**Issue by ithinkicancode** [yurique/embedded-files#15]
Hi yurique, I'm getting the following error and stack trace with sbt-embedded-files 0.2.1. I'm using sbt 1.4.9 (currently having a reported issue with sbt 1.5.x so I'm stuck with 1.4.9):

```console
java.lang.NoSuchMethodError: sbt.internal.FileChangesMacro$.rescope(Lsbt/Scope;Lsbt/TaskKey;)Lsbt/TaskKey;
	at com.yurique.embedded.sbt.EmbeddedFilesPlugin$.projectSettings$lzycompute(EmbeddedFilesPlugin.scala:91)
	at com.yurique.embedded.sbt.EmbeddedFilesPlugin$.projectSettings(EmbeddedFilesPlugin.scala:26)
	at sbt.internal.Load$.$anonfun$resolveProject$3(Load.scala:1039)
	at scala.collection.immutable.List.flatMap(List.scala:366)
	at sbt.internal.Load$.autoPluginSettings$1(Load.scala:1039)
	at sbt.internal.Load$.expandSettings$1(Load.scala:1058)
	at sbt.internal.Load$.$anonfun$resolveProject$10(Load.scala:1061)
	at scala.collection.IndexedSeqOptimized.foldLeft(IndexedSeqOptimized.scala:60)
	at scala.collection.IndexedSeqOptimized.foldLeft$(IndexedSeqOptimized.scala:68)
	at scala.collection.mutable.WrappedArray.foldLeft(WrappedArray.scala:38)
	at sbt.internal.Load$.expandSettings$1(Load.scala:1060)
	at sbt.internal.Load$.$anonfun$resolveProject$1(Load.scala:1065)
	at sbt.internal.Load$.timed(Load.scala:1382)
	at sbt.internal.Load$.resolveProject(Load.scala:1027)
	at sbt.internal.Load$.finalizeProject$1(Load.scala:908)
	at sbt.internal.Load$.discoverAndLoad$1(Load.scala:928)
	at sbt.internal.Load$.loadTransitive(Load.scala:940)
	at sbt.internal.Load$.load$1(Load.scala:876)
	at sbt.internal.Load$.discoverAndLoad$1(Load.scala:932)
	at sbt.internal.Load$.loadTransitive(Load.scala:940)
	at sbt.internal.Load$.load$1(Load.scala:876)
	at sbt.internal.Load$.discoverAndLoad$1(Load.scala:932)
	at sbt.internal.Load$.loadTransitive(Load.scala:940)
	at sbt.internal.Load$.load$1(Load.scala:876)
	at sbt.internal.Load$.discoverAndLoad$1(Load.scala:932)
	at sbt.internal.Load$.loadTransitive(Load.scala:940)
	at sbt.internal.Load$.load$1(Load.scala:876)
	at sbt.internal.Load$.discoverAndLoad$1(Load.scala:932)
	at sbt.internal.Load$.loadTransitive(Load.scala:940)
	at sbt.internal.Load$.load$1(Load.scala:876)
	at sbt.internal.Load$.discoverAndLoad$1(Load.scala:932)
	at sbt.internal.Load$.loadTransitive(Load.scala:940)
	at sbt.internal.Load$.load$1(Load.scala:876)
	at sbt.internal.Load$.loadTransitive(Load.scala:973)
	at sbt.internal.Load$.loadProjects$1(Load.scala:726)
	at sbt.internal.Load$.$anonfun$loadUnit$11(Load.scala:729)
	at sbt.internal.Load$.timed(Load.scala:1382)
	at sbt.internal.Load$.$anonfun$loadUnit$1(Load.scala:729)
	at sbt.internal.Load$.timed(Load.scala:1382)
	at sbt.internal.Load$.loadUnit(Load.scala:688)
	at sbt.internal.Load$.$anonfun$builtinLoader$4(Load.scala:486)
	at sbt.internal.BuildLoader$.$anonfun$componentLoader$5(BuildLoader.scala:180)
	at sbt.internal.BuildLoader.apply(BuildLoader.scala:245)
	at sbt.internal.Load$.loadURI$1(Load.scala:548)
	at sbt.internal.Load$.loadAll(Load.scala:564)
	at sbt.internal.Load$.loadURI(Load.scala:494)
	at sbt.internal.Load$.load(Load.scala:473)
	at sbt.internal.Load$.$anonfun$apply$1(Load.scala:242)
	at sbt.internal.Load$.timed(Load.scala:1382)
	at sbt.internal.Load$.apply(Load.scala:242)
	at sbt.internal.Load$.defaultLoad(Load.scala:55)
	at sbt.BuiltinCommands$.liftedTree1$1(Main.scala:934)
	at sbt.BuiltinCommands$.doLoadProject(Main.scala:934)
	at sbt.BuiltinCommands$.$anonfun$loadProjectImpl$2(Main.scala:887)
	at sbt.Command$.$anonfun$applyEffect$4(Command.scala:150)
	at sbt.Command$.$anonfun$applyEffect$2(Command.scala:145)
	at sbt.Command$.process(Command.scala:189)
	at sbt.MainLoop$.$anonfun$processCommand$5(MainLoop.scala:243)
	at scala.Option.getOrElse(Option.scala:189)
	at sbt.MainLoop$.process$1(MainLoop.scala:243)
	at sbt.MainLoop$.processCommand(MainLoop.scala:276)
	at sbt.MainLoop$.$anonfun$next$5(MainLoop.scala:163)
	at sbt.State$StateOpsImpl$.runCmd$1(State.scala:289)
	at sbt.State$StateOpsImpl$.process$extension(State.scala:325)
	at sbt.MainLoop$.$anonfun$next$4(MainLoop.scala:163)
	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
	at sbt.MainLoop$.next(MainLoop.scala:163)
	at sbt.MainLoop$.run(MainLoop.scala:144)
	at sbt.MainLoop$.$anonfun$runWithNewLog$1(MainLoop.scala:119)
	at sbt.io.Using.apply(Using.scala:27)
	at sbt.MainLoop$.runWithNewLog(MainLoop.scala:112)
	at sbt.MainLoop$.runAndClearLast(MainLoop.scala:66)
	at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:51)
	at sbt.MainLoop$.runLogged(MainLoop.scala:42)
	at sbt.StandardMain$.runManaged(Main.scala:193)
	at sbt.xMain$.$anonfun$run$8(Main.scala:102)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
	at scala.Console$.withIn(Console.scala:230)
	at sbt.internal.util.Terminal$.withIn(Terminal.scala:560)
	at sbt.internal.util.Terminal$.$anonfun$withStreams$1(Terminal.scala:350)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
	at scala.Console$.withOut(Console.scala:167)
	at sbt.internal.util.Terminal$.$anonfun$withOut$2(Terminal.scala:550)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
	at scala.Console$.withErr(Console.scala:196)
	at sbt.internal.util.Terminal$.withOut(Terminal.scala:550)
	at sbt.internal.util.Terminal$.withStreams(Terminal.scala:350)
	at sbt.xMain$.run(Main.scala:86)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sbt.internal.XMainConfiguration.run(XMainConfiguration.scala:83)
	at sbt.xMain.run(Main.scala:46)
	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:111)
	at xsbt.boot.Launch$.withContextLoader(Launch.scala:131)
	at xsbt.boot.Launch$.run(Launch.scala:111)
	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:37)
	at xsbt.boot.Launch$.launch(Launch.scala:120)
	at xsbt.boot.Launch$.apply(Launch.scala:20)
	at xsbt.boot.Boot$.runImpl(Boot.scala:56)
	at xsbt.boot.Boot$.main(Boot.scala:18)
	at xsbt.boot.Boot.main(Boot.scala)
[error] java.lang.NoSuchMethodError: sbt.internal.FileChangesMacro$.rescope(Lsbt/Scope;Lsbt/TaskKey;)Lsbt/TaskKey;
```

**Comment by yurique** [comment]
Hi! This is interesting. Thanks for reporting this.

So plugins built with sbt 1.5.x can't be used in sbt 1.4.x, am I understanding this correctly? 

I'll revert back to 1.4.x and publish the 0.2.2 in a few minutes.

In the meantime, you can use the 0.2.0 version – there have been no functionality changes in 0.2.1.

**Comment by yurique** [comment]
@ithinkicancode `v0.2.2` is out, could you please verify if it works for you?

**Comment by ithinkicancode** [comment]
Thanks. v0.2.2 works for me. To be honest, I'm not sure if the problem was related to sbt 1.5.x. It's just I'm using 1.4.9 instead of 1.5.x. I'm closing this issue now.
